
# Site settings
title: Jordan Shivers
email: shivers@rice.edu
description: > # this means to ignore newlines until "baseurl:"
  soft matter | rheology | statistical mechanics | biophysics
url: "https://jordanshivers.github.io"
github_username:  jordanshivers
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima

header_pages:
 - index.md
 - research.md
 - papers.md
 - cv.md
 - gallery.md
 - contact.md
 - extras.md
